global:
  scrape_interval: 15s

scrape_configs:

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  # - job_name: "dcgm_node01"

  #   static_configs:
  #     - targets: ["localhost:9400"]

  - job_name: "nvidia_gpu_exporter"
    static_configs:
      - targets: ["nvidia_smi_exporter:9835"]
