global:
  scrape_interval: 30s

scrape_configs:

  - job_name: "node_exporter"
    scrape_interval: 30s
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "nvidia_gpu_exporter"
    scrape_interval: 30s
    static_configs:
      - targets: ["nvidia_smi_exporter:9835"]
  
  - job_name: "cadvisor"
    scrape_interval: 30s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "nvitop-exporter"
    scrape_interval: 30s
    static_configs:
      - targets: ["nvitop-exporter:5050"]